spring:
    application:
        name: ToDoList2
    
    profiles:
        active: ${ACTIVE_PROFILE:local}
    
    datasource:
        url: ${DB_CONNECT_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update